#ifndef COMMONHEAD
#define COMMONHEAD
#include <QWidget>
#include <QString>
#include <QDebug>
#include <QList>
#include <QStringList>
#include <QFile>
#include <QTextStream>
#include <QFont>
#include <QDir>
#include <QIODevice>
#include <QProcess>
#include <QTextCodec>
#include <QHash>
#include <QMap>
#include <QPointer>
#include <QObject>
#include <QThread>
#include <QUrl>
#include <QFileInfo>
#include <QStandardItemModel>
#include <QFileSystemModel>
#include <QMovie>
#include <QIcon>
#include <QMultiHash>
#include <QRegExp>
#include <QMouseEvent>
#include <QPoint>
#include <QVector>
#include <QListWidgetItem>
#include <QTimer>
#include <QDateTime>
#endif // COMMONHEAD
